version: '3.9'

services:
  db-service:
    build: db-service
    ports:
      - '8000:8000'
    volumes:
      - ./db-service:/code
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000"]
      interval: 15s
      timeout: 10s
      retries: 5
    environment:
      - "RECOMMENDER_HOST=recommender"

  news-aggregator-frontend:
    build: news-aggregator-frontend
    ports:
      - '5173:5173'
    volumes:
      - ./news-aggregator-frontend:/code
    depends_on:
      db-service:
        condition: service_healthy

  aggregator:
    build: aggregator
    ports:
      - '8010:8010'
    volumes:
      - ./aggregator:/code
    depends_on:
      db-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8010"]
      interval: 15s
      timeout: 10s
      retries: 5
    environment:
      - "DB_HOST=db-service"

  annotator:
    build: annotator
    ports:
      - '8020:8020'
    volumes:
      - ./annotator:/code
    depends_on:
      aggregator:
        condition: service_healthy
    environment:
      - "SUBSCRIBER_IP=annotator"
      - "PUBLISHER_IP=aggregator"
      - "DB_HOST=db-service"
  
  recommender:
    build: recommender
    ports:
      - '8030:8030'
    volumes:
      - ./recommender:/code
    depends_on:
      db-service:
        condition: service_healthy
    environment:
      - "DB_HOST=db-service"
